# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=5, max_digits=20)),
                ('end_time', models.DecimalField(decimal_places=5, max_digits=20)),
                ('text', models.CharField(max_length=50)),
                ('textCH', models.CharField(blank=True, max_length=50)),
                ('textEN', models.CharField(blank=True, max_length=50)),
                ('textJP', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(max_length=10)),
                ('composer', models.CharField(blank=True, max_length=10)),
                ('lyricist', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('videoURL', models.CharField(max_length=15)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('viewNumber', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=10)),
                ('gender', models.DecimalField(decimal_places=1, max_digits=1)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Viewlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewTimes', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='rating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song'),
        ),
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='lyrics',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.User'),
        ),
    ]
